apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: two_carol
subjects:
- kind: ServiceAccount
  name: carol
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: two
  apiGroup: rbac.authorization.k8s.io
